 const audio1=new Audio("song1.mp3");
 const audio2=new Audio("song2.mp3");
 const audio3=new Audio("song3.mp3");
 const audio4=new Audio("song4.mp3");
 const audio5=new Audio("song5.mp3");
 const audio6=new Audio("song6.mp3");
 const audio7=new Audio("song7.mp3");
 const audio8=new Audio("song8.mp3");
 const audio09=new Audio("song09 .mp3");
 const audio10=new Audio("song10.mp3");
 const audio11=new Audio("song11.mp3");
 const audio12=new Audio("song12.mp3");
 const audio13=new Audio("song13.mp3");
 const audio14=new Audio("song14.mp3");
 const audio15=new Audio("song15.mp3");
 const audio16=new Audio("song16.mp3");
 const audio17=new Audio("song17.mp3");
 const audio18=new Audio("song18.mp3");
 const audio19=new Audio("song19.mp3");
 const audio20=new Audio("song20.mp3");
 const audio21=new Audio("song21.mp3");
 const audio22=new Audio("song22.mp3");
 const audio23=new Audio("song23.mp3");
 const audio24=new Audio("song24.mp3");
 const audio25=new Audio("song25.mp3");
 const audio26=new Audio("song26.mp3");
 const audio27=new Audio("song27.mp3");
 const audio28=new Audio("song28.mp3");
 const audio29=new Audio("song29.mp3");
 const audio30=new Audio("song30.mp3");
document.querySelector(".btn1").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio1.play();
})
document.querySelector(".btn2").addEventListener("click",function(){
    audio1.pause();

})
document.querySelector(".btn3").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio2.play();
})
document.querySelector(".btn4").addEventListener("click",function(){
    audio2.pause();

})
document.querySelector(".btn5").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio3.play();
})
document.querySelector(".btn6").addEventListener("click",function(){
    audio3.pause();

})
document.querySelector(".btn7").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio4.play();
})
document.querySelector(".btn8").addEventListener("click",function(){
    audio4.pause();

})
document.querySelector(".btn9").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio5.play();
})
document.querySelector(".btn10").addEventListener("click",function(){
    audio5.pause();

})
document.querySelector(".btn11").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio6.play();
})
document.querySelector(".btn12").addEventListener("click",function(){
    audio6.pause();

})
document.querySelector(".btn13").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio7.play();
})
document.querySelector(".btn14").addEventListener("click",function(){
    audio7.pause();

})
document.querySelector(".btn15").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio8.play();
})
document.querySelector(".btn16").addEventListener("click",function(){
    audio8.pause();

})
document.querySelector(".btn17").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio09.play();
})
document.querySelector(".btn18").addEventListener("click",function(){
    audio09.pause();

})
document.querySelector(".btn19").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio10.play();
})
document.querySelector(".btn20").addEventListener("click",function(){
    audio10.pause();

})
document.querySelector(".btn21").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio11.play();
})
document.querySelector(".btn22").addEventListener("click",function(){
    audio11.pause();

})
document.querySelector(".btn23").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio12.play();
})
document.querySelector(".btn24").addEventListener("click",function(){
    audio12.pause();

})
document.querySelector(".btn25").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio13.play();
})
document.querySelector(".btn26").addEventListener("click",function(){
    audio13.pause();

})
document.querySelector(".btn27").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio14.play();
})
document.querySelector(".btn28").addEventListener("click",function(){
    audio14.pause();

})
document.querySelector(".btn29").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio15.play();
})
document.querySelector(".btn30").addEventListener("click",function(){
    audio15.pause();

})
document.querySelector(".btn31").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio16.play();
})
document.querySelector(".btn32").addEventListener("click",function(){
    audio16.pause();

})
document.querySelector(".btn33").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio17.play();
})
document.querySelector(".btn34").addEventListener("click",function(){
    audio17.pause();

})
document.querySelector(".btn35").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio18.play();
})
document.querySelector(".btn36").addEventListener("click",function(){
    audio18.pause();
})
document.querySelector(".btn37").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio19.play();
})
document.querySelector(".btn38").addEventListener("click",function(){
    audio19.pause();

})
document.querySelector(".btn39").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio20.play();
})
document.querySelector(".btn40").addEventListener("click",function(){
    audio20.pause();
})
document.querySelector(".btn41").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio21.play();
})
document.querySelector(".btn42").addEventListener("click",function(){
    audio21.pause();
})
document.querySelector(".btn43").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio22.play();
})
document.querySelector(".btn44").addEventListener("click",function(){
    audio22.pause();

})
document.querySelector(".btn45").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio23.play();
})
document.querySelector(".btn46").addEventListener("click",function(){
    audio23.pause();

})
document.querySelector(".btn47").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio24.play();
})
document.querySelector(".btn48").addEventListener("click",function(){
    audio24.pause();

})
document.querySelector(".btn49").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio25.play();
})
document.querySelector(".btn50").addEventListener("click",function(){
    audio25.pause();

})
document.querySelector(".btn51").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio26.play();
})
document.querySelector(".btn52").addEventListener("click",function(){
    audio26.pause();

})
document.querySelector(".btn53").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio27.play();
})
document.querySelector(".btn54").addEventListener("click",function(){
    audio27.pause();

})
document.querySelector(".btn55").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio28.play();
})
document.querySelector(".btn56").addEventListener("click",function(){
    audio28.pause();

})
document.querySelector(".btn57").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio29.play();
})
document.querySelector(".btn58").addEventListener("click",function(){
    audio29.pause();

})
document.querySelector(".btn59").addEventListener("click",function(){
    audio1.pause();
    audio2.pause();
    audio3.pause();
    audio4.pause();
    audio5.pause();
    audio6.pause();
    audio6.pause();
    audio7.pause();
    audio8.pause();
    audio09.pause();
    audio10.pause();
    audio11.pause();
    audio12.pause();
    audio13.pause();
    audio14.pause();
    audio15.pause();
    audio16.pause();
    audio17.pause();
    audio18.pause();
    audio19.pause();
    audio20.pause();
    audio21.pause();
    audio22.pause();
    audio23.pause();
    audio24.pause();
    audio25.pause();
    audio26.pause();
    audio27.pause();
    audio28.pause();
    audio29.pause();
    audio30.pause();
    audio30.play();
})
document.querySelector(".btn60").addEventListener("click",function(){
    audio30.pause();

})